from __future__ import annotations

from typing import Any, Protocol


class RuleAdapter(Protocol):
    def reset(self, seed: int | None = None) -> Any: ...

    def clone_state(self, state: Any) -> Any: ...

    def get_current_player(self, state: Any) -> int: ...

    def get_legal_actions(self, state: Any, player_id: int) -> list[int]: ...

    def step(self, state: Any, player_id: int, action: int) -> Any: ...

    def is_terminal(self, state: Any) -> bool: ...

    def get_scores(self, state: Any) -> list[float]: ...

    def get_winner(self, state: Any) -> int | None: ...

    def get_public_info(self, state: Any) -> dict: ...

    def get_private_info(self, state: Any, player_id: int) -> dict: ...

    def get_state_hash(self, state: Any) -> str: ...

